### ISSUE TITLE
Committed offset is off by one?

### ISSUE THREAD

**Issue by mharju** [Mayvenn/kafka-component#1]
Thanks a lot for your great effort on this component. I'm having issues with commits being missed from the Kafka side (there is always one pending message for my topics).

I was reading through the Gregor documentation and http://weftio.github.io/gregor/gregor.core.html#var-commit-offsets.21 the async version says that 

>  The  committed offset should be the next message your application will consume, i.e. lastProcessedMessageOffset + 1."

The `latest-offsets` method does not increase the offset received from `gregor/poll` so I was wondering if this could be the cause? It seems that replacing `:offset offset` with `:offset (inc offset)` seems to be working like I expect, i.e. the lag of 1 is not visible on the Kafka's offset reporting tool.

If this is the wrong reason, I'd be happy to hear what else could be wrong, since no exceptions get generated and `consume-offsets!` is being called properly.

**Comment by sheelc** [comment]
Thanks for filing this issue @mharju! You are correct that it is off by one on the commit step.

It looks like it was broken in this recent [commit](https://github.com/Mayvenn/kafka-component/commit/a0882e02e724cf1d5553f3ae98dda8f958004b85). We'll get it fixed up today with a newly released version and then close out this issue.

**Comment by jeffh** [comment]
Hey @mharju,

I've just pushed a fix and will be publishing to clojars soon. Thanks for reporting this 👍

**Comment by jeffh** [comment]
Cut a release to `0.5.6` fixes this.

**Comment by jeffh** [comment]
Er, based on some feedback and my sad eagerness to fix this before the morning rush, I've bumped another to `0.5.7` which should fix it.

**Comment by sheelc** [comment]
@jeffh I don't think 0.5.7 is on clojars, can you check?

**Comment by mharju** [comment]
Wow, thank you for your swift response. Keep up the good work!

**Comment by jeffh** [comment]
Deployed. It should be there. I might have not actually deployed it prior (but did commit the tag).
